### PR TITLE
Add function to check if country code is from a SEPA country

### PR DESCRIPTION
**Pull request by EarthlingRich**
Add isSEPACountry function to check if a country code is from a SEPA country. I needed this functionality for a project, because next to valid IBAN's we only want to accept IBAN's from SEPA countries. I think this will be a good addition to this package.

Used the following list for the SEPA countries.
https://www.iban.com/structure

### CODE REVIEW

**Comment by EarthlingRich** [comment]
@Simplify Got time to look at this?

**Comment by Simplify** [comment]
Hi @EarthlingRich,
Sorry about late reaction, it took me a while to find some time to check this out. I'll make new release with this code included today or tomorrow.
Thank you for your contribution!

**Comment by Simplify** [comment]
Version 3.1.0 released with your PR.

**Comment by EarthlingRich** [comment]
Great thx! :)

**Pull request merged**
