### PR TITLE
Optimize bundle size by decreasing size country map

### PR DESCRIPTION
**Pull request by NextNebula**
### Changes proposed in this pull request:
The country map declared properties which could be inferred as empty or false, this made the bundle bigger than it needs to be. This PR decreases the bundle size by 28%.

### Tests

- [x] I have added test(s)
- [ ] My change does not need new tests

### ChangeLog

- [x] I have added entry in `ChangeLog` file (if not, please do so)

### CODE REVIEW

**Comment by NextNebula** [comment]
I made changes to keep the exported typings the same, but because of that getCountrySpecifications() now needs to do some calculations. I don't think this function is used much.

**Review by Simplify — APPROVED** [review]

**Comment by Simplify** [comment]
Hi @NextNebula ,
Thank you for your contribution! 
Indeed, `getCountrySpecifications()` is not used much. In 4.0 I'll be breaking API anyway, so will probably remove calculations in that release.

**Comment by eemeli** [comment]
@Simplify This was a breaking change to a public API. Before this, `getCountrySpecifications()` returned an object that could be modified in order to e.g. add a country code. After this change, such modifications have no effect.

Specifically, our use case was to add the country code `RF` in order to use the internal mod 97-10 validation for creditor references.

**Comment by eemeli** [comment]
Thanks, but we ended up writing our own mod 97-10 validator.

**Pull request merged**
